// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxbeTOID-kZFPZ2EHtvIyLoCOkiDIYhY',
    appId: '1:657146195047:web:14cf3e669ddb82f33038c2',
    messagingSenderId: '657146195047',
    projectId: 'clean-earth-project-929d9',
    authDomain: 'clean-earth-project-929d9.firebaseapp.com',
    storageBucket: 'clean-earth-project-929d9.firebasestorage.app',
    measurementId: 'G-9JCKEXF9K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3PXxfIrqD-8_wFec7kWR3knklm1tnv4',
    appId: '1:657146195047:android:321664f9a24e86973038c2',
    messagingSenderId: '657146195047',
    projectId: 'clean-earth-project-929d9',
    storageBucket: 'clean-earth-project-929d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7eMcrfKehhCVNjgu5OaLlY7egiWqA4Q',
    appId: '1:657146195047:ios:263419238b58aef73038c2',
    messagingSenderId: '657146195047',
    projectId: 'clean-earth-project-929d9',
    storageBucket: 'clean-earth-project-929d9.firebasestorage.app',
    iosBundleId: 'com.cleanearthproject.cleanEarthProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7eMcrfKehhCVNjgu5OaLlY7egiWqA4Q',
    appId: '1:657146195047:ios:263419238b58aef73038c2',
    messagingSenderId: '657146195047',
    projectId: 'clean-earth-project-929d9',
    storageBucket: 'clean-earth-project-929d9.firebasestorage.app',
    iosBundleId: 'com.cleanearthproject.cleanEarthProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxbeTOID-kZFPZ2EHtvIyLoCOkiDIYhY',
    appId: '1:657146195047:web:af2f45c8255c6a4e3038c2',
    messagingSenderId: '657146195047',
    projectId: 'clean-earth-project-929d9',
    authDomain: 'clean-earth-project-929d9.firebaseapp.com',
    storageBucket: 'clean-earth-project-929d9.firebasestorage.app',
    measurementId: 'G-3PPK45GL58',
  );
}
